# * LSP configuration

# Nil
[language-server.nil]
command = "nil"

# Nixd
[language-server.nixd]
command = "nixd"

# Simple completions language server
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 10     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = true       # enable snippets
feature_unicode_input = true  # enable "unicode input"

# * Languages configuration

[[language]]
name = "git-commit"
language-servers = [ "scls" ]

[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = [ "nix" ]
shebangs = []
comment-token = "#"
language-servers = [ "scls", "nixd" ]
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "nix"
source = { git = "https://github.com/nix-community/tree-sitter-nix", rev = "1b69cf1fa92366eefbe6863c184e5d2ece5f187d" }

[[language]]
name = "purescript"
auto-format = true
language-servers = [ "purescript-language-server", "scls" ]

# introduce a new language to enable completion on any doc by forcing set language with :set-language stub
[[language]]
name = "text"
scope = "text.text"
file-types = []
shebangs = []
roots = []
auto-format = false
language-servers = [ "scls" ]

[[language]]
name = "kanata"
scope = "source.kanata"
file-types = [ "kbd" ]
comment-tokens = [ ";;" ]
block-comment-tokens = [
  { start = "#|", end = "|#" }
]

[[grammar]]
name = "kanata"
source = { git = "https://github.com/postsolar/tree-sitter-kanata", rev = "a6213d06ea6efa432702bbbc6b4c5dcddc21df2a" }

