plugin {
  hy3 {
    no_gaps_when_only = false
    node_collapse_policy = 2
    group_inset = 20
    tab_first_window = false

    # policy controlling what windows will be focused using `hy3:movefocused`
    # 0 = focus strictly by layout, don't attempt to skip windows that are obscured by another one
    # 1 = do not focus windows which are entirely obscured by a floating window
    # 2 = when `hy3:movefocus` layer is `samelayer` then use focus policy 0 (focus strictly by layout)
    #     when `hy3:movefocus` layer is `all` then use focus policy 1 (don't focus obscured windows)
    # focus_obscured_windows_policy = <int> # default: 2
    focus_obscured_windows_policy = 0

    # which layers should be considered when changing focus with `hy3:movefocus`?
    # samelayer = only focus windows on same layer as the source window (floating or tiled)
    # all       = choose the closest window irrespective of the layout
    # tiled     = only choose tiled windows, not especially useful but permitted by parser
    # floating  = only choose floating windows, not especially useful but permitted by parser
    # default_movefocus_layer = <string>    # default: `samelayer`
    default_movefocus_layer = all

    # undocumented, amount of pixels a floating window travels on hy3:movewindow
    kbd_shift_delta = 10

    tabs {
      text_center = yes
      text_font = $monospaceFont
      text_height = 8
      text_padding = 0
      # col.text.active = 0xff$foreground
      # col.text.inactive = 0x55$foreground
      # col.urgent =
      # col.text.urgent =
    }
    autotile {
      enable = yes
    }
  }
}

# Some good presets for tabs

# No background, just text
# height = 12
# padding = 3
# render_text = yes
# text_height = 10
# col.active = 0x00ffffff
# col.inactive = 0x00ffffff
# col.text.active = 0xff2FBDEB
# col.text.inactive = 0xffffffff

# No text, just a strip of background.
# Same color for active and inactive, with inactive alpha being 55.
# height = 3
# padding = 0
# rounding = 0
# render_text = no
# col.active = 0xff......
# col.inactive = 0x55......

