# focus change
bind = SUPER      , left , hy3:movefocus, l, visible
bind = SUPER      , down , hy3:movefocus, d, visible
bind = SUPER      , up   , hy3:movefocus, u, visible
bind = SUPER      , right, hy3:movefocus, r, visible
bind = SUPER ALT  , left , hy3:movefocus, l
bind = SUPER ALT  , down , hy3:movefocus, d
bind = SUPER ALT  , up   , hy3:movefocus, u
bind = SUPER ALT  , right, hy3:movefocus, r

bind = SUPER SHIFT, code:34     , hy3:changefocus, lower # braceleft
bind = SUPER SHIFT, code:35     , hy3:changefocus, raise # braceright
bind = SUPER ALT  , bracketleft , hy3:changefocus, bottom
bind = SUPER ALT  , bracketright, hy3:changefocus, top

# node moving / resizing
# binde = SUPER SHIFT, left , exec, $scripts/move-floating-or-tiled-win.zsh left
# binde = SUPER SHIFT, down , exec, $scripts/move-floating-or-tiled-win.zsh down
# binde = SUPER SHIFT, up   , exec, $scripts/move-floating-or-tiled-win.zsh up
# binde = SUPER SHIFT, right, exec, $scripts/move-floating-or-tiled-win.zsh right
binde = SUPER SHIFT  , left , hy3:movewindow, left
binde = SUPER SHIFT  , down , hy3:movewindow, down
binde = SUPER SHIFT  , up   , hy3:movewindow, up
binde = SUPER SHIFT  , right, hy3:movewindow, right
binde = SUPER CONTROL, left , hy3:resizenode, -8 0
binde = SUPER CONTROL, down , hy3:resizenode, 0 -8
binde = SUPER CONTROL, up   , hy3:resizenode, 0 8
binde = SUPER CONTROL, right, hy3:resizenode, 8 0

# node manipulation
bind = SUPER, Q           , hy3:killactive
bind = SUPER, D           , hy3:makegroup  , opposite
bind = SUPER, S           , hy3:changegroup, opposite
bind = SUPER, bracketleft , hy3:expand     , shrink
bind = SUPER, bracketright, hy3:expand     , expand
bind = SUPER, semicolon   , hy3:expand     , base

# move to workspace silent
bind = SUPER ALT, 1, hy3:movetoworkspace, 1
bind = SUPER ALT, 2, hy3:movetoworkspace, 2
bind = SUPER ALT, 3, hy3:movetoworkspace, 3
bind = SUPER ALT, 4, hy3:movetoworkspace, 4
bind = SUPER ALT, 5, hy3:movetoworkspace, 5
bind = SUPER ALT, 6, hy3:movetoworkspace, 6
bind = SUPER ALT, 7, hy3:movetoworkspace, 7
bind = SUPER ALT, 8, hy3:movetoworkspace, 8
bind = SUPER ALT, 9, hy3:movetoworkspace, 9
bind = SUPER ALT, 0, hy3:movetoworkspace, 10

# move to workspace
bind = SUPER SHIFT, 1, exec, hyprctl dispatch hy3:movetoworkspace 1
bind = SUPER SHIFT, 2, exec, hyprctl dispatch hy3:movetoworkspace 2
bind = SUPER SHIFT, 3, exec, hyprctl dispatch hy3:movetoworkspace 3
bind = SUPER SHIFT, 4, exec, hyprctl dispatch hy3:movetoworkspace 4
bind = SUPER SHIFT, 5, exec, hyprctl dispatch hy3:movetoworkspace 5
bind = SUPER SHIFT, 6, exec, hyprctl dispatch hy3:movetoworkspace 6
bind = SUPER SHIFT, 7, exec, hyprctl dispatch hy3:movetoworkspace 7
bind = SUPER SHIFT, 8, exec, hyprctl dispatch hy3:movetoworkspace 8
bind = SUPER SHIFT, 9, exec, hyprctl dispatch hy3:movetoworkspace 9
bind = SUPER SHIFT, 0, exec, hyprctl dispatch hy3:movetoworkspace 10

# tabs
binde = SUPER      , Tab, hy3:focustab   , right, wrap
binde = SUPER SHIFT, Tab, hy3:focustab   , left , wrap
bind  = SUPER SHIFT, T  , hy3:changegroup, toggletab
bind  = SUPER      , T  , exec           , hyprctl dispatch hy3:makegroup opposite; hyprctl dispatch hy3:changegroup toggletab

# mouse
bindn = , mouse:272, hy3:focustab, mouse

