plugin {
  hyprtrails {
    color = rgba(cccccc55)
    bezier_step = 0.05 # float (0.0 - 1.0) - lower means smoother curve
    # points_per_step # int - ?
    history_points = 10 # int - trail "length"
    history_step = 2 # int - higher means choppier animation
  }
}

