plugin {
  overview {
    # ...................................
    # layout
    # in px
    panelHeight = 200

    workspaceMargin = 20
    # area on top of the wss
    reservedArea = 0

    workspaceBorderSize = 4
    hideTopLayers = yes
    showEmptyWorkspace = no

    # ...................................
    # behavior
    exitOnClick = no
    switchOnDrop = yes

  }
}

