# meta

bind  = SUPER SHIFT, F12      , exit
bind  = SUPER SHIFT, R        , exec, hyprctl reload
bind  = SUPER      , Q        , killactive
bind  = SUPER      , A        , focuscurrentorlast
bindm = SUPER      , mouse:272, movewindow
bindm = SUPER      , mouse:273, resizewindow

binde  = SUPER      , minus    , exec, $scripts/gaps.zsh inner sub 3
binde  = SUPER      , equal    , exec, $scripts/gaps.zsh inner add 3
binde  = SUPER   ALT, minus    , exec, $scripts/gaps.zsh outer sub 3
binde  = SUPER   ALT, equal    , exec, $scripts/gaps.zsh outer add 3

# programs

bind = SUPER      , Return, exec, footclient
bind = SUPER ALT  , Return, exec, foot
bind = SUPER SHIFT, Return, exec, footclient -a '-float -wh45 -center'

bind = SUPER, R, exec, footclient -a '-float -wh30 -center -noshadow -dimaround -border1' launcher
bind = SUPER, B, exec, footclient -a '-float -wh30 -center' open-clipboard

bind = SUPER, w, exec, $BROWSER

bind = SUPER      , Space, exec, footclient -a '-float -wh30 -center' sh -c 'out="$(unicode-picker all)"; [ -n "$out" ] && printf %s "$out" | wl-copy -p -n'
bind = SUPER SHIFT, Space, exec, footclient -a '-float -wh30 -center' sh -c 'out="$(unicode-picker emoji)"; [ -n "$out" ] && printf %s "$out" | wl-copy -p -n'

bind = , Print, exec, screenshot

# window state toggles

bind = SUPER      , grave, fullscreen, 1
bind = SUPER SHIFT, grave, fullscreen, 0
bind = SUPER      , F    , togglefloating
bind = SUPER CTRL , O    , toggleopaque

# workspaces

bind = SUPER CONTROL      , Tab, workspace, m+1
bind = SUPER CONTROL SHIFT, Tab, workspace, m-1

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

bind = SUPER ALT, 1, movetoworkspacesilent, 1
bind = SUPER ALT, 2, movetoworkspacesilent, 2
bind = SUPER ALT, 3, movetoworkspacesilent, 3
bind = SUPER ALT, 4, movetoworkspacesilent, 4
bind = SUPER ALT, 5, movetoworkspacesilent, 5
bind = SUPER ALT, 6, movetoworkspacesilent, 6
bind = SUPER ALT, 7, movetoworkspacesilent, 7
bind = SUPER ALT, 8, movetoworkspacesilent, 8
bind = SUPER ALT, 9, movetoworkspacesilent, 9
bind = SUPER ALT, 0, movetoworkspacesilent, 10

# audio

bind  = , F1, exec, pamixer -t
binde = , F2, exec, pamixer -d 5 --allow-boost --set-limit 150
binde = , F3, exec, pamixer -i 5 --allow-boost --set-limit 150

bindl = , XF86AudioPlay,  exec, playerctl play-pause
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioNext,  exec, playerctl next
bindl = , XF86AudioPrev,  exec, playerctl previous

# no-op submap

bind   = SUPER SHIFT, Z, submap, noop
submap = noop
bind   = , Escape, submap, reset
submap = reset

# gestures

gestures {
  workspace_swipe = yes
  workspace_swipe_fingers = 3
  workspace_swipe_distance = 200
  workspace_swipe_min_speed_to_force = 0
  workspace_swipe_cancel_ratio = 0.3
  workspace_swipe_direction_lock = no
  workspace_swipe_forever = yes
}

