# fullscreen and centering
windowrulev2 = float,          class: (-float)
windowrulev2 = fullscreen,     class: (-fullscreen)
windowrulev2 = fakefullscreen, class: (-fakefullscreen)
windowrulev2 = center,         class: (-center)

# size
windowrulev2 = size 20% 20%, class: (-wh20)
windowrulev2 = size 25% 25%, class: (-wh25)
windowrulev2 = size 30% 30%, class: (-wh30)
windowrulev2 = size 35% 35%, class: (-wh35)
windowrulev2 = size 40% 40%, class: (-wh40)
windowrulev2 = size 45% 45%, class: (-wh45)
windowrulev2 = size 50% 50%, class: (-wh50)
windowrulev2 = size 55% 55%, class: (-wh55)
windowrulev2 = size 60% 60%, class: (-wh60)

# opacity
windowrulev2 = opacity 0.2,  class: (-opacity20)
windowrulev2 = opacity 0.3,  class: (-opacity30)
windowrulev2 = opacity 0.4,  class: (-opacity40)
windowrulev2 = opacity 0.5,  class: (-opacity50)
windowrulev2 = opacity 0.6,  class: (-opacity60)
windowrulev2 = opacity 0.7,  class: (-opacity70)
windowrulev2 = opacity 0.8,  class: (-opacity80)
windowrulev2 = opacity 0.85, class: (-opacity85)
windowrulev2 = opacity 0.9,  class: (-opacity90)
windowrulev2 = opacity 0.95, class: (-opacity95)
windowrulev2 = opaque,       class: (-opaque)
windowrulev2 = forcergbx,    class: (-fullopaque)

# border size
windowrulev2 = bordersize 0, class: (-border0)
windowrulev2 = bordersize 1, class: (-border1)
windowrulev2 = bordersize 2, class: (-border2)
windowrulev2 = bordersize 3, class: (-border3)
windowrulev2 = bordersize 4, class: (-border4)
windowrulev2 = bordersize 5, class: (-border5)
windowrulev2 = bordersize 6, class: (-border6)
windowrulev2 = bordersize 7, class: (-border7)
windowrulev2 = bordersize 8, class: (-border8)
windowrulev2 = bordersize 9, class: (-border9)

# dim, shadow, x-ray
windowrulev2 = nodim,     class: (-nodim)
windowrulev2 = noshadow,  class: (-noshadow)
windowrulev2 = dimaround, class: (-dimaround)
windowrulev2 = xray 1,    class: (-xray)
windowrulev2 = xray 0,    class: (-noxray)

